name: Deploy Supabase Functions

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-edge-functions:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repo's latest code
      - uses: actions/checkout@v3

      # 2) Install Node.js & the Supabase CLI
      - name: Install Node.js and supabase CLI
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g supabase

      # 3) Supabase Login (with your personal access token from secrets)
      - name: Supabase Login
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # 4) Deploy your functions
      - name: Deploy generate-recipe
        run: supabase functions deploy generate-recipe

      - name: Deploy modify-recipe
        run: supabase functions deploy modify-recipe