name: Deploy Supabase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: tehwjzcwlejiuntymwal   # or your real project ref

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest  # or specify a version like "1.72.2"

      - run: supabase functions deploy --project-ref $PROJECT_ID
